apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedido-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedido-service
  template:
    metadata:
      labels:
        app: pedido-service
    spec:
      containers:
        - name: pedido-service
          image: seuusuario/pedido-service:1.0
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/microsservicos_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            # Propriedades para chamadas HTTP dentro do cluster
            - name: CLIENTES_BASE_URL
              value: http://cliente-service:8081
            - name: PRODUTOS_BASE_URL
              value: http://produto-service:8082
---
apiVersion: v1
kind: Service
metadata:
  name: pedido-service
spec:
  selector:
    app: pedido-service
  ports:
    - port: 8083
      targetPort: 8083
  type: NodePort
